console.log('hello,world');
var $header = document.querySelector('h1');
console.log($header);
console.dir($header);
var $explanation = document.querySelector('#explanation');
console.dir($explanation);
var $hint = document.querySelector('.hint');
console.dir($hint);
var $paragraphs = document.querySelectorAll('p');
console.log($paragraphs);
var $links = document.querySelectorAll('.example-link');
console.log($links);
